### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by CountTails** [slice-of-life/frontend#3]
Tried to build the angular application, but failed. I ran to following

```bash
$ npm install
$ ng build
```

This issue prevents deployment

**Comment by CountTails** [comment]
Error message is too big to post here, see if you can reproduce first.

**Comment by MatthewIsayan** [comment]
devDependency:  "@angular-devkit/build-angular"
was out of date, fixed via:
```
$ npm update 
$ npm audit fix --force
```
